# Site settings
title: Joyful Coding
description: Portfolio of Drew Miller
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://joyfulcoding.github.io" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Drew Miller
user_description: Web Developer at Joyful Coding
user_title: Web Developer
email: millerdrew@gmail.com
twitter_username: joyfulcoding
github_username:  millerdrew

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
#  - title: Tags
#    url: /tags
#  - title: About Me
#    url: /about

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
